# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@master
    - run: |
        yarn install
        yarn run build
        
    - name: commit
      run: |
        git config --global user.email status102@outlook.com
        git config --global user.name status102_action
        git add .
        git commit -m "update" -a
        
    - name: Push changes
      uses: ad-m/github-push-action@action-generate
      with:
        github_token: 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
